# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Table

# Model Form Field configuration
form: $/macrobit/horeca/models/table/fields.yaml

# Model Class name
modelClass: Macrobit\Horeca\Models\Table

# Default redirect location
defaultRedirect: macrobit/horeca/tables

# Create page
create:
    title: Create Table
    redirect: macrobit/horeca/tables/update/:id
    redirectClose: macrobit/horeca/tables

# Update page
update:
    title: Edit Table
    redirect: macrobit/horeca/tables
    redirectClose: macrobit/horeca/tables

# Preview page
preview:
    title: Preview Table