# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Payment Info

# Model Form Field configuration
form: $/macrobit/horeca/models/paymentinfo/fields.yaml

# Model Class name
modelClass: Macrobit\Horeca\Models\PaymentInfo

# Default redirect location
defaultRedirect: macrobit/horeca/paymentinfos

# Create page
create:
    title: Create Payment Info
    redirect: macrobit/horeca/paymentinfos/update/:id
    redirectClose: macrobit/horeca/paymentinfos

# Update page
update:
    title: Edit Payment Info
    redirect: macrobit/horeca/paymentinfos
    redirectClose: macrobit/horeca/paymentinfos

# Preview page
preview:
    title: Preview Payment Info