# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Firm

# Model Form Field configuration
form: $/macrobit/horeca/models/firm/fields.yaml

# Model Class name
modelClass: Macrobit\Horeca\Models\Firm

# Default redirect location
defaultRedirect: macrobit/horeca/firms

# Create page
create:
    title: Create Firm
    redirect: macrobit/horeca/firms/update/:id
    redirectClose: macrobit/horeca/firms

# Update page
update:
    title: Edit Firm
    redirect: macrobit/horeca/firms
    redirectClose: macrobit/horeca/firms

# Preview page
preview:
    title: Preview Firm