# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Placement

# Model Form Field configuration
form: $/macrobit/horeca/models/placement/fields.yaml

# Model Class name
modelClass: Macrobit\Horeca\Models\Placement

# Default redirect location
defaultRedirect: macrobit/horeca/placements

# Create page
create:
    title: Create Placement
    redirect: macrobit/horeca/placements/update/:id
    redirectClose: macrobit/horeca/placements

# Update page
update:
    title: Edit Placement
    redirect: macrobit/horeca/placements
    redirectClose: macrobit/horeca/placements

# Preview page
preview:
    title: Preview Placement