# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Placement

# Model Form Field configuration
form: $/macrobit/foodcatalog/models/placement/fields.yaml

# Model Class name
modelClass: Macrobit\FoodCatalog\Models\Placement

# Default redirect location
defaultRedirect: macrobit/foodcatalog/placements

# Create page
create:
    title: Create Placement
    redirect: macrobit/foodcatalog/placements/update/:id
    redirectClose: macrobit/foodcatalog/placements

# Update page
update:
    title: Edit Placement
    redirect: macrobit/foodcatalog/placements
    redirectClose: macrobit/foodcatalog/placements

# Preview page
preview:
    title: Preview Placement