# ===================================
#  Relation Behavior Config
# ===================================

tables:
    label: Tables
    view:
        toolbarButtons: create|delete
        list:
            columns:
                name: macrobit.horeca::lang.field.name
    manage:
        showSearch: true
        list: $/macrobit/horeca/models/table/columns.yaml
        form: $/macrobit/horeca/models/table/fields.yaml