# ===================================
#  Relation Behavior Config
# ===================================

tables:
    label: Tables
    view:
        toolbarButtons: create|delete
        list: $/macrobit/horeca/models/table/columns.yaml
    manage:
        showSearch: true
        list: $/macrobit/horeca/models/table/columns.yaml
        form: $/macrobit/horeca/models/table/fields.yaml