# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Tag

# Model Form Field configuration
form: $/macrobit/horeca/models/tag/fields.yaml

# Model Class name
modelClass: Macrobit\Horeca\Models\Tag

# Default redirect location
defaultRedirect: macrobit/horeca/tags

# Create page
create:
    title: Create Tag
    redirect: macrobit/horeca/tags/update/:id
    redirectClose: macrobit/horeca/tags

# Update page
update:
    title: Edit Tag
    redirect: macrobit/horeca/tags
    redirectClose: macrobit/horeca/tags

# Preview page
preview:
    title: Preview Tag