# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/macrobit/horeca/models/node/columns.yaml

# Model Class name
modelClass: Macrobit\Horeca\Models\Node

# List Title
title: Manage Nodes

# Link URL for each record
recordUrl: macrobit/horeca/nodes/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Displays the tree view
showTree: false
showCheckboxes: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
        
# Filter configuration
filter: 
    scopes:
        firm:
            label: Firm
            modelClass: Macrobit\Horeca\Models\Firm
            nameFrom: name
            conditions: firm_id in (:filtered)